<?php
return[
    'classes'=>[
        1=>[
            \App\Lib\Classes\MediaBlocker::class,
            \App\Lib\Classes\Start::class,
            \App\Lib\Classes\Help::class,
            \App\Lib\Classes\Banner::class,
            \App\Lib\Classes\Profile::class

        ],
        2=>[
            \App\Lib\Classes\LoginAccount::class,
            \App\Lib\Classes\BuyVipCallBack::class
        ],
        3=>[
            \App\Lib\Classes\AddAcount::class,
            \App\Lib\Classes\GetLink::class,
            \App\Lib\Classes\BuyVip::class,
        ]
    ]
];
